collections:
  episodes:
    output: true

title: Community Service Hour
description: Open source every week.
url: https://hour.gg
twitter_username: fulldecent

defaults:
  -
    scope:
      path: ""
      type: episodes
    values:
      layout: episode
      excerpt_separator: <!--end of quick notes-->
      permalink: /:collection/:name

# https://jekyllrb.com/docs/configuration/liquid/
liquid:
  error_mode: strict
#  strict_variables: true
  strict_filters: true
